version: "3"
services:
  ds:
    container_name: ds
    restart: always
    environment:
      - DB_CON_STR=mongodb://mongo:27017/testDB
    build: .
    ports:
      - "3002:3002"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"